language: go
go:
  - 1.11.x
  - 1.12.x

branches:
  only:
    - master

cache:
  directories:
    - vendor/
    - bin/

env:
  - GO111MODULE=on

before_script:
  - go mod vendor
  - cd golangci-lint
  - 'curl -sfL \
      https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
      | sh -s v1.17.1'

script:
  - ./bin/golangci-lint run
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
